# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/konstantin/Projects/marshmallow_gif

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/konstantin/Projects/marshmallow_gif

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/konstantin/Projects/marshmallow_gif/CMakeFiles /home/konstantin/Projects/marshmallow_gif/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/konstantin/Projects/marshmallow_gif/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/build
.PHONY : app/fast

#=============================================================================
# Target rules for targets named marshmallow_gif

# Build rule for target.
marshmallow_gif: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 marshmallow_gif
.PHONY : marshmallow_gif

# fast build rule for target.
marshmallow_gif/fast:
	$(MAKE) -f CMakeFiles/marshmallow_gif.dir/build.make CMakeFiles/marshmallow_gif.dir/build
.PHONY : marshmallow_gif/fast

src/app.o: src/app.cpp.o

.PHONY : src/app.o

# target to build an object file
src/app.cpp.o:
	$(MAKE) -f CMakeFiles/marshmallow_gif.dir/build.make CMakeFiles/marshmallow_gif.dir/src/app.cpp.o
.PHONY : src/app.cpp.o

src/app.i: src/app.cpp.i

.PHONY : src/app.i

# target to preprocess a source file
src/app.cpp.i:
	$(MAKE) -f CMakeFiles/marshmallow_gif.dir/build.make CMakeFiles/marshmallow_gif.dir/src/app.cpp.i
.PHONY : src/app.cpp.i

src/app.s: src/app.cpp.s

.PHONY : src/app.s

# target to generate assembly for a file
src/app.cpp.s:
	$(MAKE) -f CMakeFiles/marshmallow_gif.dir/build.make CMakeFiles/marshmallow_gif.dir/src/app.cpp.s
.PHONY : src/app.cpp.s

src/config.o: src/config.cpp.o

.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i

.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s

.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/gif.o: src/gif.cpp.o

.PHONY : src/gif.o

# target to build an object file
src/gif.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/gif.cpp.o
.PHONY : src/gif.cpp.o

src/gif.i: src/gif.cpp.i

.PHONY : src/gif.i

# target to preprocess a source file
src/gif.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/gif.cpp.i
.PHONY : src/gif.cpp.i

src/gif.s: src/gif.cpp.s

.PHONY : src/gif.s

# target to generate assembly for a file
src/gif.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/gif.cpp.s
.PHONY : src/gif.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/marshmallow_gif.dir/build.make CMakeFiles/marshmallow_gif.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/marshmallow_gif.dir/build.make CMakeFiles/marshmallow_gif.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/marshmallow_gif.dir/build.make CMakeFiles/marshmallow_gif.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/setting.o: src/setting.cpp.o

.PHONY : src/setting.o

# target to build an object file
src/setting.cpp.o:
	$(MAKE) -f CMakeFiles/marshmallow_gif.dir/build.make CMakeFiles/marshmallow_gif.dir/src/setting.cpp.o
.PHONY : src/setting.cpp.o

src/setting.i: src/setting.cpp.i

.PHONY : src/setting.i

# target to preprocess a source file
src/setting.cpp.i:
	$(MAKE) -f CMakeFiles/marshmallow_gif.dir/build.make CMakeFiles/marshmallow_gif.dir/src/setting.cpp.i
.PHONY : src/setting.cpp.i

src/setting.s: src/setting.cpp.s

.PHONY : src/setting.s

# target to generate assembly for a file
src/setting.cpp.s:
	$(MAKE) -f CMakeFiles/marshmallow_gif.dir/build.make CMakeFiles/marshmallow_gif.dir/src/setting.cpp.s
.PHONY : src/setting.cpp.s

src/start_setup.o: src/start_setup.cpp.o

.PHONY : src/start_setup.o

# target to build an object file
src/start_setup.cpp.o:
	$(MAKE) -f CMakeFiles/marshmallow_gif.dir/build.make CMakeFiles/marshmallow_gif.dir/src/start_setup.cpp.o
.PHONY : src/start_setup.cpp.o

src/start_setup.i: src/start_setup.cpp.i

.PHONY : src/start_setup.i

# target to preprocess a source file
src/start_setup.cpp.i:
	$(MAKE) -f CMakeFiles/marshmallow_gif.dir/build.make CMakeFiles/marshmallow_gif.dir/src/start_setup.cpp.i
.PHONY : src/start_setup.cpp.i

src/start_setup.s: src/start_setup.cpp.s

.PHONY : src/start_setup.s

# target to generate assembly for a file
src/start_setup.cpp.s:
	$(MAKE) -f CMakeFiles/marshmallow_gif.dir/build.make CMakeFiles/marshmallow_gif.dir/src/start_setup.cpp.s
.PHONY : src/start_setup.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... app"
	@echo "... marshmallow_gif"
	@echo "... src/app.o"
	@echo "... src/app.i"
	@echo "... src/app.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/gif.o"
	@echo "... src/gif.i"
	@echo "... src/gif.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/setting.o"
	@echo "... src/setting.i"
	@echo "... src/setting.s"
	@echo "... src/start_setup.o"
	@echo "... src/start_setup.i"
	@echo "... src/start_setup.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

